import {
  ArrowFatLineRightIcon,
  ArrowLineDownIcon,
  ArrowRightIcon,
  ArrowsClockwiseIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CursorClickIcon,
  ExportIcon,
  FireSimpleIcon,
  GearIcon,
  GithubLogoIcon,
  InfoIcon,
  LightbulbIcon,
  LinkedinLogoIcon,
  MusicNotesIcon,
  PaletteIcon,
  PauseIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlusIcon,
  TrashIcon,
  XIcon,
} from "@phosphor-icons/react";

export const icons = {
  common: {
    arrow_right: ArrowRightIcon,
    chart_bar: ChartBarIcon,
    check_circle: CheckCircleIcon,
    cursor_click: CursorClickIcon,
    fire_simple: FireSimpleIcon,
    gear: GearIcon,
    info: InfoIcon,
    lightbulb: LightbulbIcon,
    music_notes: MusicNotesIcon,
    palette: PaletteIcon,
  },
  function: {
    arrow_fat_line_right: ArrowFatLineRightIcon,
    arrow_line_down: ArrowLineDownIcon,
    arrows_clockwise: ArrowsClockwiseIcon,
    export: ExportIcon,
    pause: PauseIcon,
    pencil_simple: PencilSimpleIcon,
    play: PlayIcon,
    plus: PlusIcon,
    trash: TrashIcon,
    x: XIcon,
  },
  brand: {
    github_logo: GithubLogoIcon,
    linkedin_logo: LinkedinLogoIcon,
  },
} as const;
